# Etapa 1: build Angular
FROM node:23 AS build-angular

WORKDIR /app
COPY app-angular/package*.json ./
RUN npm install
COPY app-angular/ ./
#RUN npm run app-angular build --configuration production
#RUN ng build app-angular --configuration production
RUN npx ng build app-angular --configuration production

# Etapa 2: servir com Nginx
FROM nginx:alpine

COPY --from=build-angular /app/dist/app-angular/browser /usr/share/nginx/html
COPY app-angular/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
