services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: app-hub-api
    ports:
      - "8081:8081"
    environment:
      - URLH2=jdbc:h2:tcp://192.168.10.7:9092/~/h2/bin/data/app-db
      - USRH2=deivy
      - PWDH2=duocore
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: app-hub-front
    ports:
      - "4200:80"
    depends_on:
      - backend
