services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: app-hub-api
    ports:
      - "8081:8081"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: app-hub-front
    ports:
      - "4200:80"
    depends_on:
      - backend
