#!/user/bin/env groovy
pipeline{
    agent none
    stages{
        stage('build'){
            agent{
                docker {
                    image 'maven:3.9.6-eclipse-temurin-21'
                    args '-v /var/jenkins_home/.m2:/root/.m2'
                }
            }
            steps{
                sh "mvn package -Dmaven.test.skip=true"
            }
       }
    }
}