#!/user/bin/env groovy
pipeline{
    agent none
    stages{
        stage('build'){
            agent{
                docker {image 'maven'}
            }
            steps{
                sh "maven package -Dmaven.test.skip=true"
            }
       }
    }
}